GET http://localhost:3000

###
POST  http://localhost:3000/api/createUser
content-type: application/json

{
    "name":"Adon Biju",
    "number":"12345678905",
    "emailId":"adon@gmail.com"
}

###

GET   http://localhost:3000/api/getAllUsers

###
PUT  http://localhost:3000/api/updateUser/adon@gmail.com
content-type: application/json

{
    "name":"Adon Biju",
    "number":"987654321"
}